name: generate animation

on:
  # запуск каждые 24 часа
  schedule:
    - cron: "0 */24 * * *"

  # запуск вручную
  workflow_dispatch:

  # запуск при пуше в main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # создаёт анимацию с графом коммитов пользователя arane1223
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: arane1223
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # публикует результат в репозиторий arane1223/arane1223 (в ветку output)
      - name: push github-contribution-grid-snake.svg to arane1223 repo
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          repo: arane1223/arane1223
        env:
          GITHUB_TOKEN: ${{ secrets.ARANE1223_TOKEN }}
